# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DJabberd-Authen-DBIC
version:      0.01
version_from: lib/DJabberd/Authen/DBIC.pm
installdirs:  site
requires:
    Digest:                        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
